language: node_js
node_js:
  - "7"
  - "6"
branches:
  only: 
    - master
env:
  - CXX=g++-4.8
dist: trusty
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
      - oracle-java8-set-default
    chrome: stable
before_script:
  - export DISPLAY=:99.0; sh -e /etc/init.d/xvfb start
before_install:
  - "npm install -g npm@^4"
  - "google-chrome-stable --headless --disable-gpu --remote-debugging-port=9222 http://localhost &"
bundler_args: --retry 0
notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/c42ddc125fe6bbfccb48
    on_success: change
    on_failure: always
    on_start: never
