language: node_js
node_js:
- '8'
- '6'
git:
  depth: 1
cache:
  yarn: true
  directories:
  - node_modules
  - generator-theia/node_modules
branches:
  only:
  - master
os:
  - linux
  - osx
env:
  global:
  - secure: es511klr3A8rLVIQ+ZxWkYl2/OLaZYzHpLH94O0EqFDC05t7sk76WOD+9fVT0jkINUKt7sK4Nozv19GmNYxFVXKaWwAH9jt7sHKYgbfCr+vTg58z9jyposMZSGEgsGPSbFn5DxPS7KdWbfQDEjxX18yiKMKN9k+7XwkC8p+WSgy4I30M5Y4YXffQooEwjqJpTdkpOm6p+o6t99mp3ufaxG5VOLtSwsZ0r3cKJo0rbqKxJGA62eNYLYksQ7PsFHDE2stQ8IDxFNXOrXB6ocwwd7KGphJIofU/t1UCXjpsGn0Ozr4LYvSpvl9nKQBmA3prKuAOnygLZh0YfYACIoIpBFa0/igxdX7j7INgp50Q+6CHRWwCb+YqZPgJ297EZi5mVKYNlAh0OeKKTo0NanunWR2pnzj29MGzR40wJqPVhQBRQvaKannwpoY5opK8MWi9jnDDY3xpzgZ8na3yOkw9wQ+a2nUm13BZnWmMDODGnaf9vy9eQ7bB26eiU2VSHlNWeniqDMY81sjqBlst22bHR4IgsI4qkh5UXMyyvMKbXltUIXERdCv1yK/Faa/VJ0Qrs+mk+G23bkT8/1f6cHBhjiVJX5HhXLcN3lHxImi+K9NkuCn8g+okX+SfD2lT5OPpRYHS8Jb51frNUIDWqWqRcjCioNjcuup2o6nbTlJaFb0=
matrix:
   include:
     - os: linux
       env: CXX=g++-4.8
     - os: osx
       env: CXX=c++
   exclude:
     - os: osx
       node_js: '6'
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8
    - oracle-java8-set-default
    chrome: stable
before_script:
  - if [ ${TRAVIS_OS_NAME} = "linux" ]; then 
      export DISPLAY=:99.0; sh -e /etc/init.d/xvfb start ;
    fi 
before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - export PATH=$HOME/.yarn/bin:$PATH ;
  - if [ ${TRAVIS_OS_NAME} = "linux" ]; then google-chrome-stable --headless --disable-gpu --remote-debugging-port=9222 http://localhost \&  ; fi
install: yarn
script: 
  - if [ ${TRAVIS_OS_NAME} = "linux" ]; then 
      travis_retry yarn test ;
    else
      travis_retry yarn test:theia ;
    fi
notifications:
  webhooks:
    urls:
    - https://webhooks.gitter.im/e/c42ddc125fe6bbfccb48
    on_success: change
    on_failure: always
    on_start: never
jobs:
  include:
  - stage: deploy
    node_js: '6'
    install: skip
    script: skip
    before_deploy:
      - printf "//registry.npmjs.org/:_authToken=${NPM_AUTH_TOKEN}\n" >> ~/.npmrc
      - yarn
    deploy:
      provider: script
      script: yarn run publish:next
      on:
        branch: master
      skip_cleanup: true
