shallow_clone: true

branches:
  only:
  - master

platform:
  - x64

install:
  - cinst yarn
  - ps: npm install --global --production windows-build-tools

before_build:
  - node --version && npm --version && yarn --version && python --version

build_script:
  - yarn

test_script:
  - yarn run test